### ISSUE TITLE
Age verification

### ISSUE THREAD

**Issue by gamingc6** [FeezyHendrix/Insta-mass-account-creator#1]
Hey,
yesterday I tried to use your Tool and i really like The was it generates all The Profile stuff. But during The registration process Instagram asks whether you are old enough or Not. Could you please add this to your Code?

I already tried to get The Element By it‘s xPath, But it didnt work

**Comment by FeezyHendrix** [comment]
Ok cool, a screen shot would help thought, cause i never encountered that problem

**Comment by gamingc6** [comment]
Sorry for my late answer, i tried it again but the problem still occurs. Maybe the reason is the german version of Instagram.

Maybe you can encounter the problem with a proxy or the latest version of your country now?

![image](https://user-images.githubusercontent.com/40039491/41683344-9fc1cc3e-74da-11e8-8ad0-1e804ecdcbee.png)

**Comment by FeezyHendrix** [comment]
oh okay would try to fix soon.

**Comment by gamingc6** [comment]
have you already figured out how to fix the issue?

**Comment by FeezyHendrix** [comment]
Try changing your proxy to another country, pending the time this is resolved

**Comment by kelleymuro** [comment]
Are you using proxies to create accounts or just letting it run?

**Comment by tobeyond** [comment]
Any solution for this?

**Comment by anykindofusername** [comment]
ANy solution?
