### ISSUE TITLE
Is there a way to bypass sms verification?

### ISSUE THREAD

**Issue by MatteoAntolini** [FeezyHendrix/Insta-mass-account-creator#100]
I know that I can do it manually but this will not be an insta mass account generator if it's not automatic.

There is an app for android named Talktone. It gives you one free phone number and one free message and it worked for instagram authentication. I tried to make an android emulator but it so complicated

**Comment by FeezyHendrix** [comment]
Hi,
Currently, we have implemented email verification, this is a feature we are also looking into.

**Comment by MatteoAntolini** [comment]
Awesome, I await news

**Comment by SC4MM3R** [comment]
Hello, how are you, has this worked for you?  If so how do I contact you?
