### ISSUE TITLE
Add error message and dump record to a text file

### ISSUE THREAD

**Issue by sauky** [FeezyHendrix/Insta-mass-account-creator#13]
Just minor revision from your codes after clicking submit button, so any error message will be captured alongside with username into firebase db and dump it also to a text file :
                         .................
                            submit.click()
                            sleep(3)
                            try:
                                alert  = driver.find_element_by_xpath("//*[@role='alert']")
                                alert = alert.text
                            except:
                                alert=""
                                pass

                            print('Registering....'+name+','+alert)
                            try:
                                with open('storedDB.txt', 'a') as outcsv:
                                    writer = csv.writer(outcsv, delimiter=';', quotechar='"', quoting=csv.QUOTE_NONE, lineterminator='\n')
                                    #text = name+','+alert
                                    #print(text )
                                    writer.writerow([name, alert])
                                outcsv.close()
                            except:
                                pass
                            storeinfirebase(name,alert)

                            sleep(10)
                            driver.close()
                            if "Sorry" in alert:
                                return True
..........
..........
..........
...........
...........
...........

for i in range(0, config.Config['amount_of_run']):
    if create_account():
        break

**Comment by FeezyHendrix** [comment]
Hi, Thank you very much. Kindly create a pull request so I can easily update.
