### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by BlizzarOfficial** [FeezyHendrix/Insta-mass-account-creator#14]
get just this issue when i run the botcore.py with "python botcore.py"

Traceback (most recent call last):
  File "botcore.py", line 12, in <module>
    from modules.storeusernametofirebase import storeinfirebase
  File "C:\insta\modules\storeusernametofirebase.py", line 1, in <module>
    from firebase import firebase
  File "C:\Program Files (x86)\Python\lib\site-packages\firebase\__init__.py", line 3
    from .async import process_pool

Config = {
    "password" : "DAMNPASSWORD",
    "firebase_url" : "https://insta-7c2bb.firebaseio.com/",
    "proxy_server" : "213.168.210.76", #213.168.210.76 sample proxy server to not let instagram block your ip
    "has_proxy_file" : True, #change to True to use proxy list file 
    "proxy_file" : {
        "proxy_server_txt_file_path" : "Assets/proxies.txt", # input file path
        "profile_per_proxy" : 0 , # 0 creates random of number of account per proxy found, set in between 1 - 10
    },
    "amount_of_run" : 100 #amount of time to run code
}

**Comment by BlizzarOfficial** [comment]
my python version is 3.6.5 and i also tried on 3.7 
i tried pip install -r requirements.txt - in CMD with Admin rights 
i do pip update and after that pip install... 
but every time the same issue hope you can help

**Comment by FeezyHendrix** [comment]
Hi there, 
you should try using a `virtual env` for this, cause you may have python libraries crashing with each other.

**Comment by BlizzarOfficial** [comment]
i just setup a virutal env following this [Guide](https://www.youtube.com/watch?v=GBAJ7VKyEpI) but its again the same issue

(chapter2) C:\Users\stephan.dautzenberg\Desktop\realpython\chapter2>python botcore.py
Traceback (most recent call last):
  File "botcore.py", line 12, in <module>
    from modules.storeusernametofirebase import storeinfirebase
  File "C:\Users\stephan.dautzenberg\Desktop\realpython\chapter2\modules\storeusernametofirebase.py", line 1, in <module>
    from firebase import firebase
  File "C:\Users\stephan.dautzenberg\Desktop\realpython\chapter2\lib\site-packages\firebase\__init__.py", line 3
    from .async import process_pool
              ^
SyntaxError: invalid syntax

**Comment by FeezyHendrix** [comment]
pip install firebase in the virtual env.

**Comment by BlizzarOfficial** [comment]
(chapter2) C:\Users\stephan.dautzenberg\Desktop\realpython\chapter2>pip install firebase
Collecting firebase
  Could not find a version that satisfies the requirement firebase (from versions: )
No matching distribution found for firebase

**Comment by BlizzarOfficial** [comment]
i just found on google pip install python-firebase but if i try to use this my cmd say:

(chapter2) C:\Users\stephan.dautzenberg\Desktop\realpython\chapter2>pip install python-firebase
Requirement already satisfied: python-firebase in c:\users\stephan.dautzenberg\desktop\realpython\chapter2\lib\site-packages (1.2)
Requirement already satisfied: requests>=1.1.0 in c:\users\stephan.dautzenberg\desktop\realpython\chapter2\lib\site-packages (from python-firebase) (1.1.0)

(chapter2) C:\Users\stephan.dautzenberg\Desktop\realpython\chapter2>

**Comment by BlizzarOfficial** [comment]
the version of python is Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32

pip3 install .r requirements.txt make this:
```
(chapter2) C:\Users\stephan.dautzenberg\Desktop\realpython\chapter2>pip3 install -r requirements.txt
Requirement already satisfied: certifi==2018.4.16 in c:\users\stephan.dautzenberg\desktop\realpython\chapter2\lib\site-packages (from -r requirements.txt (line 1)) (2018.4.16)
Requirement already satisfied: chardet==3.0.4 in c:\users\stephan.dautzenberg\desktop\realpython\chapter2\lib\site-packages (from -r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna==2.6 in c:\users\stephan.dautzenberg\desktop\realpython\chapter2\lib\site-packages (from -r requirements.txt (line 3)) (2.6)
Requirement already satisfied: python-firebase==1.2 in c:\users\stephan.dautzenberg\desktop\realpython\chapter2\lib\site-packages (from -r requirements.txt (line 4)) (1.2)
Collecting requests==2.18.4 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Requirement already satisfied: selenium==3.12.0 in c:\users\stephan.dautzenberg\desktop\realpython\chapter2\lib\site-packages (from -r requirements.txt (line 6)) (3.12.0)
Requirement already satisfied: urllib3==1.22 in c:\users\stephan.dautzenberg\desktop\realpython\chapter2\lib\site-packages (from -r requirements.txt (line 7)) (1.22)
Installing collected packages: requests
  Found existing installation: requests 1.1.0
    Uninstalling requests-1.1.0:
      Successfully uninstalled requests-1.1.0
Successfully installed requests-2.18.4
```
but after this the same issue on python botcore.py
```
(chapter2) C:\Users\stephan.dautzenberg\Desktop\realpython\chapter2>python botcore.py
Traceback (most recent call last):
  File "botcore.py", line 12, in <module>
    from modules.storeusernametofirebase import storeinfirebase
  File "C:\Users\stephan.dautzenberg\Desktop\realpython\chapter2\modules\storeusernametofirebase.py", line 1, in <module>
    from firebase import firebase
  File "C:\Users\stephan.dautzenberg\Desktop\realpython\chapter2\lib\site-packages\firebase\__init__.py", line 3
    from .async import process_pool
              ^
SyntaxError: invalid syntax
```

**Comment by BlizzarOfficial** [comment]
**Update** 

i just fixed the problem it was cause of the version i completly uninstalled Python and installed it again on version 3.6.5 now it works... buuuuut when the chrom window appears they enter the account data the comes the verification of the age and then the window close and the cmd say this:

`Traceback (most recent call last):
  File "botcore.py", line 115, in create_account
    driver.get('https://www.instagram.com/')
  File "C:\Users\stephan.dautzenberg\Desktop\realpython\Instagram\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 326, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\stephan.dautzenberg\Desktop\realpython\Instagram\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "C:\Users\stephan.dautzenberg\Desktop\realpython\Instagram\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.16299 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botcore.py", line 153, in <module>
    create_account()
  File "botcore.py", line 149, in create_account
    driver.close()
  File "C:\Users\stephan.dautzenberg\Desktop\realpython\Instagram\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 681, in close
    self.execute(Command.CLOSE)
  File "C:\Users\stephan.dautzenberg\Desktop\realpython\Instagram\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "C:\Users\stephan.dautzenberg\Desktop\realpython\Instagram\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.16299 x86_64)
`

**Comment by FeezyHendrix** [comment]
This is a common problem that comes with the proxy you use, some countries proxy requires age verification. try using other countries.

**Comment by BlizzarOfficial** [comment]
do you know a country which dont requires age verification? 
i tried some but always the same...

**Comment by FeezyHendrix** [comment]
There's a default proxy in the comment

**Comment by BlizzarOfficial** [comment]
this one has age verification-> #213.168.210.76 sample proxy server to not let instagram block your ip
and the default proxys in proxy.txt also

**Comment by FeezyHendrix** [comment]
Oh okay. I don't know of any for now.

**Comment by BlizzarOfficial** [comment]
when do you think you add the feature that the age verfication work?

**Comment by FeezyHendrix** [comment]
Currently working on it.

**Comment by sanjsingh07** [comment]
try any indian proxies.

**Comment by sanjsingh07** [comment]
try this 

28 121.46.95.65:8080

**Comment by BlizzarOfficial** [comment]
dont work same as with every proxy...

**Comment by L13ut3n4nt** [comment]
Hello,
remove the driver.close () lines from if else leaving the code like this:

from time import sleep
from random import randint

import modules.config as config
#importing generated info
import modules.generateaccountinformation as accnt
from modules.storeusernametofirebase import storeinfirebase 
#library import 
from selenium import webdriver
from selenium.webdriver.common.keys import Keys # and Krates


def create_account():
    try:
        if config.Config['has_proxy_file'] == False :
            chrome_options = webdriver.ChromeOptions()
            chrome_options.add_argument('--proxy-server=%s' % config.Config['proxy_server'])

            #creating a chrome object instance to open browser
            driver = webdriver.Chrome(chrome_options=chrome_options)
            driver.get('https://www.instagram.com/')
            sleep(3)

            name = accnt.username()
            #username 
            

            #fill the email value
            email_field = driver.find_element_by_name('emailOrPhone')
            email_field.send_keys(accnt.genEmail())

            #fill the fullname value
            fullname_field = driver.find_element_by_name('fullName')
            fullname_field.send_keys(accnt.genName())

            #fill username value
            username_field = driver.find_element_by_name('username')
            username_field.send_keys(name)

            #fill password value
            password_field  = driver.find_element_by_name('password')
            passW = accnt.generatePassword() 
            password_field.send_keys(passW)

            submit = driver.find_element_by_xpath('//*[@id="react-root"]/section/main/article/div[2]/div[1]/div/form/div[6]/span/button')
            submit.click()

            print('Registering....')

            storeinfirebase(name)
            print('Fechado')

            sleep(1)
            driver.close()
        else :
            with open(config.Config['proxy_file']['proxy_server_txt_file_path'], 'r') as file :
                content = file.read().splitlines()
                for proxy in content :
                    chrome_options = webdriver.ChromeOptions()
                    chrome_options.add_argument('--proxy-server=%s' % proxy)
                    print(proxy)

                    #creating a chrome object instance to open browser
                    driver = webdriver.Chrome(chrome_options=chrome_options)

                    amount_per_proxy = config.Config['proxy_file']['profile_per_proxy']

                    if amount_per_proxy != 0 :
                        
                        print("Creating {} amount of users for this proxy".format(amount_per_proxy))

                        for i in range(0, amount_per_proxy) :
                            driver.get('https://www.instagram.com/')
                            sleep(3)
                            #username 
                            name = accnt.username()
                            
                            #fill the email value
                            email_field = driver.find_element_by_name('emailOrPhone')
                            email_field.send_keys(accnt.genEmail())

                            #fill the fullname value
                            fullname_field = driver.find_element_by_name('fullName')
                            fullname_field.send_keys(accnt.genName())

                            #fill username value
                            username_field = driver.find_element_by_name('username')
                            username_field.send_keys(name)

                            #fill password value
                            password_field  = driver.find_element_by_name('password')
                            passW = accnt.generatePassword() 
                            password_field.send_keys(passW)

                            submit = driver.find_element_by_xpath('//*[@id="react-root"]/section/main/article/div[2]/div[1]/div/form/div[6]/span/button')
                            submit.click()

                            print('Registering....')

                            storeinfirebase(name)

                            sleep(1)
                            print('Fechado amount não zero')
                    else :
                        random_number = randint(1, 20)
                        
                        print("Creating {} amount of users for this proxy".format(random_number))
                        for i in range(0, random_number):
                            driver.get('https://www.instagram.com/')
                            sleep(3)
                            #username 
                            name = accnt.username()
                            
                            #fill the email value
                            email_field = driver.find_element_by_name('emailOrPhone')
                            email_field.send_keys(accnt.genEmail())

                            #fill the fullname value
                            fullname_field = driver.find_element_by_name('fullName')
                            fullname_field.send_keys(accnt.genName())

                            #fill username value
                            username_field = driver.find_element_by_name('username')
                            username_field.send_keys(name)

                            #fill password value
                            password_field  = driver.find_element_by_name('password')
                            passW = accnt.generatePassword() 
                            password_field.send_keys(passW)

                            submit = driver.find_element_by_xpath('//*[@id="react-root"]/section/main/article/div[2]/div[1]/div/form/div[6]/span/button')
                            submit.click()

                            print('Registering....')

                            storeinfirebase(name)

                            sleep(1)
                            print('Fechado amount zero')

    except Exception as e:
        print(e)
        driver.close()


for i in range(0, config.Config['amount_of_run']):
    create_account()
