### ISSUE TITLE
Message: no such element: Unable to locate element

### ISSUE THREAD

**Issue by DerLomo** [FeezyHendrix/Insta-mass-account-creator#145]
When runing creator.py in cmd it gives that ERROR, seems it can find that element specifically cant find:
Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="emailOrPhone"]"}
And this is the full error:
DevTools listening on ws://127.0.0.1:58544/devtools/browser/95e33360-4de9-49ab-88bb-0293d31ed3f6
[7904:1972:0430/220951.572:ERROR:browser_switcher_service.cc(238)] XXX Init()
Opening Browser
Browser Opened
INFO:root:Gender: male
INFO:root:Url generated: https://it.fakenamegenerator.com/gen-male-it-it.php
INFO:root:Birthday: February 4, 1996
INFO:root:Username: cosimonapolitani14
Filling email field
Error!, Check its possible your ip might be banned

DevTools listening on ws://127.0.0.1:58566/devtools/browser/b9f7b285-06f7-4104-b77e-bb35e7d845d1
[3544:11560:0430/221007.647:ERROR:browser_switcher_service.cc(238)] XXX Init()
Opening Browser
Browser Opened
INFO:root:Gender: male
INFO:root:Url generated: https://it.fakenamegenerator.com/gen-male-it-it.php
INFO:root:Birthday: June 9, 1964
INFO:root:Username: giulianomarcelo77
Filling email field
Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="emailOrPhone"]"}
  (Session info: chrome=81.0.4044.129)

I thing it may be because i m spanish and so it can t find that because is not in english?

 - OS: Windows
 - Browser Chrome

**Comment by DerWolf12** [comment]
I saw th other post about making some lines of code from seleniumbot.py to be a comment, but doesn t work either

**Comment by alin0908** [comment]
how about opening instagram.com and changing the selector to the actual one?

**Comment by tommy2049** [comment]
same error

**Comment by florijohn** [comment]
You have to change line 55 in "seleniumbot.py" to: 

`driver.get("https://www.instagram.com/accounts/emailsignup/")`

And line 105 to 

```
submit = driver.find_element_by_xpath(
            '//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[7]/div')
```

**Comment by DerWolf12** [comment]
> 
> 
> You have to change line 55 in "seleniumbot.py" to:
> 
> `driver.get("https://www.instagram.com/accounts/emailsignup/")`
> 
> And line 105 to
> 
> ```
> submit = driver.find_element_by_xpath(
>             '//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[7]/div')
> ```

Thanks a lot buddy it worked fine, but now the bot seems stuck at the following step , the age page, why is not filling the fields?
The program just ends itself and dont fill any age despite giving a random birthday in the cmd

**Comment by florijohn** [comment]
Hey!

You just have to change some things in the selenium.py file:

Line 114
`try:

            #age_button = driver.find_element_by_xpath( "//input[@name='ageRadio' and @value='above_18']")
            #age_button.click()
            year_button = driver.find_element_by_xpath("/html/body/div[1]/section/main/div/article/div/div[1]/div/div[4]/div/div/span/span[3]/select/option[35]")
            year_button.click()
        

            sleep(2)
            next_button = driver.find_element_by_xpath("/html/body/div[1]/section/main/div/article/div/div[1]/div/div[5]/div[2]/button")
            next_button.click()

        except Exception as e :
            pass`

I simply filled the form with a fix year. But you can do it dynamic with the generated birthday by the bot itself.

Hoffe das hilft dir ;)))

**Comment by holograman01** [comment]
Thanks man it worked but i cant access the account created. it is just showing but theres no any account

**Comment by holograman01** [comment]
> next_button = driver.find_element_by_xpath("/html/body/div[1]/section/main/div/article/div/div[1]/div/div[5]/div[2]/button")

Bro thx so much. you saved my life but i have another question. When i create an account it is always going to challenge, how can it fix? please. thx

**Comment by GramCreator** [comment]
> > next_button = driver.find_element_by_xpath("/html/body/div[1]/section/main/div/article/div/div[1]/div/div[5]/div[2]/button")
> 
> Bro thx so much. you saved my life but i have another question. When i create an account it is always going to challenge, how can it be fixed? please. thx

The bot is not faking private IP & this is an easy detection.

More things, fingerprints aren't generated dynamically from a huge database, no referrer etc.
