### ISSUE TITLE
[Errno 20] Not a directory

### ISSUE THREAD

**Issue by UHaweq12** [FeezyHendrix/Insta-mass-account-creator#15]
Error Msg: 
UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by FeezyHendrix** [comment]
Hi,
 A full log of the error would be appreciated. cause I can't deduce the problem from this.

**Comment by UHaweq12** [comment]
Running on Vserver cause i wanted to do a wrapper for discord. 
Specs: debian 8 
errorlog: 
[Errno 20] Not a directory
Traceback (most recent call last):
  File "botcore.py", line 153, in <module>
    create_account()
  File "botcore.py", line 149, in create_account
    driver.close()
UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by FeezyHendrix** [comment]
Are you still using a vserver?

**Comment by UHaweq12** [comment]
yes
cant get it to work might aswell try it on my raspberry pi

**Comment by FeezyHendrix** [comment]
okay. try it would see what I can do to resolve it.

**Comment by UHaweq12** [comment]
would be great but i think u cant fix the chromium cant display error

**Comment by FeezyHendrix** [comment]
Would be expecting your feedback.

**Comment by UHaweq12** [comment]
allright just one question how do i install the reqs on windows? testing on a different system might work

**Comment by FeezyHendrix** [comment]
The requirements are quite easy just follow the steps.

**Comment by UHaweq12** [comment]
/next error:
System: Kali linux
Error: 
Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-kali2-amd64 x86_64)

**Comment by UHaweq12** [comment]
any idea?
