### ISSUE TITLE
Proxylist?

### ISSUE THREAD

**Issue by Itwww** [FeezyHendrix/Insta-mass-account-creator#16]
everytime i use a proxy it says: Instagram.com not found. 
And if it creates a account it asks if iam 18 or older. any fix? and where do you get your proxy from?

**Comment by FeezyHendrix** [comment]
Try Indian Proxies, They seem to work better.

**Comment by Itwww** [comment]
what proxy grabber do you use?

**Comment by Itwww** [comment]
and is there any proxyports that i should not use ?

**Comment by FeezyHendrix** [comment]
We are still working on that, Instagram needs to verify each account.

**Comment by Itwww** [comment]
ok. nice to hear
