### ISSUE TITLE
Any account confirmation fix yet?

### ISSUE THREAD

**Issue by UHaweq12** [FeezyHendrix/Insta-mass-account-creator#19]
^

**Comment by FeezyHendrix** [comment]
I currently need help on this

**Comment by juanmicl** [comment]
> I currently need help on this

I think you should start reversing Instagram private api (sniffing instagram requests)

**Comment by juanmicl** [comment]
I think the right way is using python requests instead of chromedriver

**Comment by FeezyHendrix** [comment]
Okay, how would I be able to verify 1000 accounts with this ? @juanmicl

**Comment by juanmicl** [comment]
you mean verify age or email verification after registration?

**Comment by juanmicl** [comment]
A nice way to email verification would be using a domain ex: "acountgenerated@mydomain.com" and a catchall email for "mydomain.com" then you will have all email verifications sent to the same email.

**Comment by FeezyHendrix** [comment]
That could work I think. could get your email so we can talk more?

**Comment by juanmicl** [comment]
contacto @ juanmi . pw <-- Remove blank spaces (cause of bots).
