### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Itwww** [FeezyHendrix/Insta-mass-account-creator#25]
Message: no such element: Unable to locate element: {"method":"name","selector":"emailOrPhone"}

**Comment by tobeyond** [comment]
I had the same. First:

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="react-root"]/section/main/article/div[2]/div[1]/div/form/div[6]/span/button"}

And after: 

Message: no such element: Unable to locate element: {"method":"name","selector":"emailOrPhone"}

**Comment by cyasinsengul** [comment]
use this xpath //*[@id="react-root"]/section/main/article/div[2]/div[1]/div/form/div[7]/div/button
