### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by NeverLucky2** [FeezyHendrix/Insta-mass-account-creator#26]
<img width="567" alt="screen shot 2018-11-05 at 1 14 25 pm" src="https://user-images.githubusercontent.com/38539234/48020915-c5d12a80-e0fc-11e8-9586-a86b8c5cb3e9.png">
I changed the config file in version 2 to nearly match the one in version 1 and added other stuff to make it work for python 3.6. However my problem here is that most of these proxies have been used before and are now blocked.
Am i supposed to create proxies myself, and if not, where do i find more proxies that aren't open?

**Comment by FeezyHendrix** [comment]
You can find more proxies. I think that's a better solution.

**Comment by tobeyond** [comment]
I had the same issue but the proxy wasn't in proxies.txt .
When using version 1, no proxy would work but the sample one. 
Maybe this is a bug when configuring the proxy script?
Where the port is defined, for exemple?

**Comment by tobeyond** [comment]
Also when using version 1, it only uses the first 3 proxies of my list.

**Comment by Hosseinhashemiir** [comment]
the same error i have... 
is there any way to pass this issue?

**Comment by NeverLucky2** [comment]
lol use version 2, not version 1
