### ISSUE TITLE
Where Does It Store Passwords

### ISSUE THREAD

**Issue by NotII123** [FeezyHendrix/Insta-mass-account-creator#28]
Where Does It Store Passwords or what is the default password

**Comment by FeezyHendrix** [comment]
the default password is the password it would use for all the account created.

**Comment by NotII123** [comment]
ok thanks

**Comment by NotII123** [comment]
Anyway to change??

**Comment by FeezyHendrix** [comment]
you can change your default password by editing the config file in the modules folder.

**Comment by NotII123** [comment]
Thanks! Can i promote this on my youtube??

**Comment by NotII123** [comment]
I cant login to the accounts

**Comment by FeezyHendrix** [comment]
okay, age verification fix should be done soon.

**Comment by NotII123** [comment]
is it verifying the files rn?

**Comment by FeezyHendrix** [comment]
No not yet

**Comment by NotII123** [comment]
ok

**Comment by NotII123** [comment]
How long till update

**Comment by NotII123** [comment]
didnt mean close

**Comment by FeezyHendrix** [comment]
I am closing this issue because its currently opened on another issue.
