### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ShawtyCode** [FeezyHendrix/Insta-mass-account-creator#29]
Tried to run this script via git bash,
got that response:

`$ py creator.py
Traceback (most recent call last):
  File "creator.py", line 1, in <module>
    from modules.config import Config
  File "C:\Users\kek\Desktop\Insta-mass-account-creator-master\modules\config.py                         ", line 14
    "amount_of_account": 10,
                       ^
SyntaxError: invalid syntax
`

my config.py looks like this:

`
author: feezyhendrix

    this is for configuration files
    notes: check Assets/proxies.txt to use your custom proxies.

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSET_DIR = os.path.join(BASE_DIR, 'Assets' )

Config = {
    "bot_type" : 1,
    "password" : "censored"
    "use_custom_proxy" : False, #default is False change to True to use a file containing multiple proxies of yours.
    "amount_of_account": 10, #amount of account you want to create make sure it doesnt exceed 50 for better performance
    "amount_per_proxy": 10, #this would be amont of account used if you have a you are using multiple proxies
    "proxy_file_path" : ASSET_DIR + "/proxies.txt"
}`

**Comment by FeezyHendrix** [comment]
It appears there is no comma after `password: censored`
