### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by Shailesh200** [FeezyHendrix/Insta-mass-account-creator#33]
I Created VirtualEnv then added chrome driver to the path and then run the creator.py file but all the proxies don't work.
Can you just tell me a step-wise more precise steps and also please tell me where are the usernames or emails are to be stored?

**Comment by FeezyHendrix** [comment]
The usernames would be stored in the Assets folder and try using custom proxies cause it appears Instagram has flag those

**Comment by Shailesh200** [comment]
I tried other proxies as well. I am getting this error.

Error!, Trying another Proxy 192.140.42.81:48164
Message: session not created: Chrome version must be >= 69.0.3497.0
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-21deepin-generic x86_64)

Error!, Trying another Proxy 192.140.42.81:48164
Error!, Trying another Proxy 110.136.205.9:33753
Error!, Trying another Proxy 92.38.45.98:58680
Error!, Trying another Proxy 1.20.97.122:45796
Error!, Trying another Proxy 119.82.253.95:54044
Error!, Trying another Proxy 195.46.181.186:34883
{u'status': u'ok', u'error_type': u'signup_block', u'errors': {u'ip': [u'The IP address you are using has been flagged as an open proxy. If you believe this to be incorrect, please visit http://help.instagram.com/']}, u'account_created': False}

**Comment by Shailesh200** [comment]
And I can not find username file in Assets folder can you have a look over it?

**Comment by Shailesh200** [comment]
Now I am getting this error:

cannot concatenate 'str' and 'SessionNotCreatedException' objects

**Comment by FeezyHendrix** [comment]
The username.txt only gets created when a n account  has been created
