### ISSUE TITLE
Installing and running  Bot

### ISSUE THREAD

**Issue by apinc14** [FeezyHendrix/Insta-mass-account-creator#34]
profile1$ python3 creator.py
Creating 10 amount of users for this proxy
can only concatenate str (not "WebDriverException") to str
Traceback (most recent call last):
  File "creator.py", line 3, in <module>
    from modules.requestbot import runBot
  File "/Users/austinpincumbe/Desktop/AcctCreation/modules/requestbot.py", line 3, in <module>
    from generateaccountinformation import genName, username, genEmail
ModuleNotFoundError: No module named 'generateaccountinformation'

**Comment by apinc14** [comment]
Any help?

**Comment by FeezyHendrix** [comment]
This is a relative import issue

**Comment by FeezyHendrix** [comment]
Change the line to .generateaccountinformation

**Comment by apinc14** [comment]
Profile1$ python3 creator.py
Creating 3 amount of users for this proxy
can only concatenate str (not "WebDriverException") to str
Traceback (most recent call last):
  File "creator.py", line 14, in <module>
    runBot()
  File "/Users/austinpincumbe/Desktop/AcctCreation/modules/requestbot.py", line 87, in runBot
    for i in range(Config['amount_of_account']):
TypeError: 'type' object is not subscriptable

**Comment by FeezyHendrix** [comment]
Okay are you sure your config is properly inputted

**Comment by apinc14** [comment]
Not positive. But I just downloaded a fresh version. installed requirements.txt. Changed the password, amount per account value, and amount per proxy value.  launched and got this error again

**Comment by FeezyHendrix** [comment]
Could you upload your to a repo
