### ISSUE TITLE
after a while the account will not open

### ISSUE THREAD

**Issue by byniniko** [FeezyHendrix/Insta-mass-account-creator#39]
I've opened 30-40 accounts. Then I went to the site. Sorry, something went wrong creating your account. Please try again soon.  gave an error.  Screenshoot ;  https://hizliresim.com/16ynVA

**Comment by byniniko** [comment]
I do not know how to do it..  Should I login to old opened accounts?

**Comment by FeezyHendrix** [comment]
Yes immediately you create the account you should be able to verify them

**Comment by byniniko** [comment]
but the accounts I open are closed due to direct violation. I'm using the ipv6 / 64 network.

**Comment by FeezyHendrix** [comment]
Ohh this is a new issue, I haven't encountered before ...

**Comment by byniniko** [comment]
I get this error when I log in to the accounts.

It was closed because it violated the terms of the account: http://instagram.com/about/legal/terms


However, this doesn't happen for your software, but when I manually add the chrome proxy and open an account on instagram, it gives the same error.

**Comment by FeezyHendrix** [comment]
Ohh it seems like a general issue
