### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by deadfishhackers** [FeezyHendrix/Insta-mass-account-creator#40]
** root@fbi:~/Downloads/Insta-mass-account-creator# python creator.py **
``Error!, Trying another Proxy 41.223.154.186:53614 Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home``

**How do i put my executable location?
Because its in the file**

**root@fbi:~/Downloads/Insta-mass-account-creator# ls
Assets creator.py modules requirements.txt
``chromedriver`` debug.log README.md**

**Comment by deadfishhackers** [comment]
root@fbi:~/Downloads/Insta-mass-account-creator# python creator.py 
Error!, Trying another Proxy 94.240.220.30:42311
Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.14.0-kali3-amd64 x86_64)

**Comment by deadfishhackers** [comment]
i dont have chrome browser i have firefox

**Comment by FeezyHendrix** [comment]
This project was configured to use chrome browser

**Comment by FeezyHendrix** [comment]
This project was configured to use chrome browser

**Comment by deadfishhackers** [comment]
what if ill download it?

**Comment by FeezyHendrix** [comment]
Yes you are suppose to download it and configure it to your path, or you can use the requests.bot

**Comment by FeezyHendrix** [comment]
Which doesn't require selenium

**Comment by deadfishhackers** [comment]
kk

**Comment by deadfishhackers** [comment]
thanks, dont close this issue wait i will test first

**Comment by deadfishhackers** [comment]
i have to create another user and reinstall all things needed for chrome '-' 

can u make this firefox supported ?

**Comment by deadfishhackers** [comment]
because i dont want to reinstall all

**Comment by deadfishhackers** [comment]
(google-chrome:16217): Gtk-WARNING **: 08:02:00.760: cannot open display: :1

**Comment by deadfishhackers** [comment]
anyone doing it using FireFox?

**Comment by deadfishhackers** [comment]
do it pls
