### ISSUE TITLE
Proxies i added aren't being used

### ISSUE THREAD

**Issue by 3iex** [FeezyHendrix/Insta-mass-account-creator#41]
Hello,

when i use version 1 in config file i get : 
`Creating 3 amount of users for this proxy`
`cannot concatenate 'str' and 'WebDriverException' objects`

and when i use version 2, it doesn't use any of the proxies i have added to the proxies.txt instead it uses from the sslproxies site while the option use custom proxy is already True and these proxies are flagged, how can i make it use the proxies i added in proxies.txt?

thanks in advance.

**Comment by mzaboss** [comment]
any update? still using random proxies from sslproxies site. not useful. all flagged.

**Comment by tolino978** [comment]
you have to enable "use_custom_proxy" in the config file
