### ISSUE TITLE
how to conf chrome driver path

### ISSUE THREAD

**Issue by BitLif3** [FeezyHendrix/Insta-mass-account-creator#43]
How i can configure chrome driver path? ty

**Comment by bambanggr** [comment]
i put the chromedriver in C 
![image](https://user-images.githubusercontent.com/8994505/55423265-bd93f300-55a7-11e9-8443-f98953dc7c3f.png)
then i set path like this below
![image](https://user-images.githubusercontent.com/8994505/55423184-99381680-55a7-11e9-8e8b-998f33561f72.png)
but still get error : 
`Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

**Comment by esamuarif** [comment]
i have thia issue 
**_python creator.py
Error!, Check its possible your ip might be banned
Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home_**
im using termux btw please help
