### ISSUE TITLE
Not working Proxy error message

### ISSUE THREAD

**Issue by Plaztomad** [FeezyHendrix/Insta-mass-account-creator#45]
Hi,  this is my error message:

Error!, Trying another Proxy 36.67.223.67:43628
Message: no such element: Unable to locate element: {"method":"name","selector":"emailOrPhone"}
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 6.3.9600 x86_64)

Could u help me please?

**Comment by FeezyHendrix** [comment]
Hi, this is a common issue, the proxy being used is not working try getting custom proxies.

**Comment by FeezyHendrix** [comment]
Theres a configuration setting in the config.py file which allows you to use custom_proxy

**Comment by Plaztomad** [comment]
https://i.ibb.co/dMXP0sX/1548674164648620563209.jpg

I uploaded a screenshot with the result after changing settings you adviced me.

**Comment by Plaztomad** [comment]
Am I creating accounts or not? Can I also manage them at the same time (for the same actions like follow/like ecc)? Thanks

**Comment by Plaztomad** [comment]
Ok but how can I use custom_proxy?

I'm in the config.py file anche changed use_custom_proxy to True

**Comment by FeezyHendrix** [comment]
Yes

**Comment by omerrciftcii** [comment]
> Ok but how can I use custom_proxy?
> 
> I'm in the config.py file anche changed use_custom_proxy to True

hello, how did you find proxies ?
