### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by tobeyond** [FeezyHendrix/Insta-mass-account-creator#47]
I stopped using it for a couple months..
So I tried selenium bot again and instagram always says they had a problem creating the account.
Maybe it blocked all the proxies?
Is requests bot working?

**Comment by tolino978** [comment]
Yes Instagram has indeed blocked a lot of open proxys. And yes the requests bot does work with some slight changes.

**Comment by FeezyHendrix** [comment]
@tolino978 hi what are the changes you have been able to  make ?

**Comment by tolino978** [comment]
@FeezyHendrix Hi i changed it so that when you have custom proxys in the proxies.txt file, it actually gets those proxys and not just gets them from sslproxies.org. Altough it isn't working right now i seem to have fucked up the code somehow, but is was working a few days ago.

**Comment by FeezyHendrix** [comment]
Do you have a repo I can check that out from?

**Comment by tolino978** [comment]
Yes I can send you an invitation link. Do you have an email adress I can send that link to?

**Comment by FeezyHendrix** [comment]
Switchdevelop1@gmail.com

**Comment by mzaboss** [comment]
@tolino978 can you send me too please? mzabossy@gmail.com thank you or push an update please.

**Comment by tolino978** [comment]
@mzaboss yes I will send you a link aswell. Altough keep in mind it isn't working right now

**Comment by deadfishhackers** [comment]
can u send me too? <a href="mailto:deadfishhackers@gmail.com>
