### ISSUE TITLE
Help on pip install -r requirements.txt

### ISSUE THREAD

**Issue by kkislmao** [FeezyHendrix/Insta-mass-account-creator#48]
I try doing this and it says that their is no such file or directory: 'requirements.txt'

**Comment by tolino978** [comment]
you need to specify the full path or change the directory. I suggest specifying the full path.

pip install -r C:\Insta-mass-account-generator\requirements.txt

As an example. Just replace C:\... with your own path.

**Comment by kkislmao** [comment]
I tried that but it still says it doesn't exist :(

**Comment by tolino978** [comment]
Can you send a screenshot of the command you typed and the error message?
