### ISSUE TITLE
chrome installer guidance

### ISSUE THREAD

**Issue by feyron89** [FeezyHendrix/Insta-mass-account-creator#49]
Hi everyone, forgive my ignorance, how do i set the path and everything for the chrome driver?
Anyone can help me in the process?

**Comment by FeezyHendrix** [comment]
[This ](https://developers.thomsonreuters.com/sites/default/files/How%20To%20Add%20ChromeDriver%20To%20System%20Variables_0.pdf 
)is a good resource to check out
