### ISSUE TITLE
Pleaseeee Helppppp!

### ISSUE THREAD

**Issue by marcobic** [FeezyHendrix/Insta-mass-account-creator#51]
![account creator error](https://user-images.githubusercontent.com/43816389/53560620-160d4600-3b4d-11e9-8638-afc4c0680d02.PNG)

Please Help!

Account creator is no more working!

It gives "Error! Trying another proxy!".

I printed the whole traceback!

Please, let's make this script work again!

**Comment by FeezyHendrix** [comment]
Hi, I would advise you get a custom proxy to run the script.

**Comment by marcobic** [comment]
I'm using custom proxies, but it gives me this error! Can you send me a list of valid proxies? Email: bicche@live.it

**Comment by FeezyHendrix** [comment]
The proxies I have are expired. Try using more of mobile proxy.
