### ISSUE TITLE
Problem with loading the creator.py file

### ISSUE THREAD

**Issue by lidoramrani** [FeezyHendrix/Insta-mass-account-creator#59]
I am experiencing a problem when loading the creator.py file.
I recieve this message:

Traceback (most recent call last):
  File "creator.py", line 3, in <module>
    from modules.requestbot import runBot
  File "/home/lidoramrani21/Insta-mass-account-creator/modules/requestbot.py", line 84
    except:
         ^
SyntaxError: invalid syntax

P.S I am using Ubuntu 18.04 Virtual Machine on Google Cloud.

Screenshot is added
![newfile](https://user-images.githubusercontent.com/48685368/54913655-e0653e00-4efb-11e9-964e-590035999d1a.PNG)

**Comment by WindsofRose** [comment]
go to in requestbot. and after this you need change except to else

**Comment by WindsofRose** [comment]
because it syntax error

**Comment by tolino978** [comment]
It's corrected now
