### ISSUE TITLE
AttributeError: 'Options' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by anselayala** [FeezyHendrix/Insta-mass-account-creator#6]
I'm not sure why I'm getting this error. I thought I've done everything correctly except find where to configure the path to chromedriver.
`  File "botcore.py", line 18, in <module>
    driver = webdriver.Chrome(chrome_options)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 95, in start
    (os.path.basename(self.path), self.start_error_message, str(e)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'Options' object has no attribute 'rfind'`

**Comment by FeezyHendrix** [comment]
From the errors above, it looks like you are using python 2.7, this is a Python 3 project

**Comment by anselayala** [comment]
Thanks for the quick response, I've done this already and only have one error now. 

`  File "botcore.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'`


I've reinstalled selenium but I'm still getting this error. Am I doing something wrong?

**Comment by FeezyHendrix** [comment]
This is a Unix type system related issue, you could try : 
`sudo easy_install selenium ` or ` sudo pip install selenium`  and since you have a two different python versions you want to do  `sudo pip3 install selenium`

**Comment by anselayala** [comment]
I guess it's the night of (t)errors. After doing what you said. I also reinstalled the requirements with pip3 to prevent any further errors with the Firebase module. However, I got introduced into a new error.
`  File "botcore.py", line 14, in <module>
    from modules.storeusernametofirebase import storeinfirebase
  File "/Users/codeacademy/Documents/Insta-mass-account-creator-master/modules/storeusernametofirebase.py", line 1, in <module>
    from firebase import firebase
  File "/usr/local/lib/python3.7/site-packages/firebase/__init__.py", line 3
    from .async import process_pool
              ^
SyntaxError: invalid syntax`

I'm getting an invalid syntax error now.  Any help, please?

**Comment by anselayala** [comment]
okay

**Comment by FeezyHendrix** [comment]
Okay upload your code to a repo, send a link and i would review

**Comment by anselayala** [comment]
https://github.com/anselayala/Insta-mass-account-creator Haven't really made any changes really just the firebase URL, pass, and proxy. Everything else was untouched.

**Comment by FeezyHendrix** [comment]
It doesn't Include your updated config
