### ISSUE TITLE
Error no such element: ageRadio

### ISSUE THREAD

**Issue by realsirjoe** [FeezyHendrix/Insta-mass-account-creator#60]
Hey there, everything seems to work fine until the over18 selection, there I get the following error:

no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name='ageRadio' and @value='above_18']"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.13.6 x86_64)

I checked "over18 sign up html" (in browser) the name and value seem correct, dont know what the issue is here.

**Comment by KewaiiGamer** [comment]
This issue still seems to occur. I don't see why closing this issue will solve anything?
