### ISSUE TITLE
"The new fake Instagram account with an unverified phone number after ~ 1-24 hours could not do any requests. All requests will be redirected to the page"

### ISSUE THREAD

**Issue by ScriptKidOver9000** [FeezyHendrix/Insta-mass-account-creator#61]
If I understand correctly, the acc can not follow or disappear after 24 hours?
If this is the case I can possibly help. I have created an Instagram ACC with an Android user agent and have now had it several days without any problems! I can still follow people etc. even Trasmail works! I'm sorry it's in german.

![wsuehfjhke](https://user-images.githubusercontent.com/48059771/55005296-03ffb580-4fdc-11e9-82c5-fddc2146cbd0.png)

I hope I have not mistaken and wasted your time. Keep it up!

**Comment by FeezyHendrix** [comment]
Oh awesome did you change anything in the code?

**Comment by FeezyHendrix** [comment]
So has to be sure you just have to use an android user agent.

**Comment by ScriptKidOver9000** [comment]
No I did not change the code. I have tested this several times in Firefox with the web development tool. But with the user agent you can do a lot. In addition to creating instagram acc, you can easily skip the verification number on Facebook or get access to private forum topics as Googlebot. Unfortunately I do not have the knowledge or a Server to help with the development of your bot. If it does not work, I'm sorry but it should! 

Kind regards ScriptKid
