### ISSUE TITLE
username() missing 1 required positional argument: 'identity'

### ISSUE THREAD

**Issue by bambanggr** [FeezyHendrix/Insta-mass-account-creator#64]
**Describe the bug**
username() missing 1 required positional argument: 'identity' Error message

**Config files**
`Config = {
    "bot_type" : 1, #change to 2 to use python requests
    "use_custom_proxy" : True, #default is False change to True to use a file containing multiple proxies of yours.
    "use_local_ip_address" : True, #default is False chnage to True to user your computers ip directly.
    "amount_of_account": 1, #amount of account you want to create make sure it doesnt exceed 50 for better performance
    "amount_per_proxy": 1, #this would be amont of account used if you have a you are using multiple proxies
    "proxy_file_path" : ASSET_DIR + "/proxies.txt",
    "email_domain": "mail.com",
    "country": "id",
    "activation_email_addr": "xxxxxxxxxxxxxxxx",
    "activation_email_pass": "xxxxxxxxxxxxxxxx",
    "activation_email_serv": "xxxxxxxxxxxxxxxx",
    "activation_email_spor": 993,
}`

**proxies.txt**
`178.150.89.13:55676
202.57.55.194:61811
197.248.60.21:43380`

**To Reproduce**
1. Run as usual
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/8994505/55424124-bf5eb600-55a9-11e9-980a-5bdad81b6875.png)

Can someone help me about this?

**Comment by bambanggr** [comment]
I think in this part : 
`#generating a username
def username(identity):
    n = str(random.randint(1,99))
    name = str(identity).lower().replace(" ","")
    username = name + n
    logging.info("Username: {}".format(username))
    return(username)`

**Comment by RiChYFanatics** [comment]
running on this error too
