### ISSUE TITLE
What is the default password for all the accounts?

### ISSUE THREAD

**Issue by Colintur2004** [FeezyHendrix/Insta-mass-account-creator#66]
Hi, I was just wondering what the default password is, thanks.

**Comment by ARKRafay** [comment]
Hey can you send me your folder. I'm getting this error "can only concatenate str (not "TypeError") to str"

**Comment by Colintur2004** [comment]
You should create a new thread for your issue :)

**Comment by ARKRafay** [comment]
I have made it but no solution. The developer also tried but can't find the root cause of this problem. I would appreciate if you can send me.

**Comment by mathias7777** [comment]
> Hi, I was just wondering what the default password is, thanks.

hey i think your password should be in the asset>module>ganerateaccinfo.py

as you can see the bot make a random number 1 and 99 number 

there are also a option for changing how to pass is generated like make text or just make some edit in the code 

exeaple return ''.join(random.choice(password_characters) for i in range(12)) < this is the original portion of code in generateaccinfo 

return 'yourpasswordhere' < you just have to change to this so you will know the password of the generated account
