### ISSUE TITLE
Not inputting information.

### ISSUE THREAD

**Issue by DaemonGFX** [FeezyHendrix/Insta-mass-account-creator#70]
Hello thanks for fixing my error it now lets me run the program and successfully open google chrome. But I have fallen into another error. When opening google chrome it just sits at instagram.com and doesn't do anything.

ERROR:
![image](https://user-images.githubusercontent.com/42479150/57314218-1bf14b80-70e9-11e9-8bb3-bb43ec2e792a.png)

I have not been IP banned and I am on windows 10 and am using the selenium bot.
Many thanks!

**Comment by halperdz** [comment]
i have same prblm

**Comment by FeezyHendrix** [comment]
This is a problem with proxy or IP not being able to open the page.
