### ISSUE TITLE
ModuleNotFoundError: No module named 'pymailutils'

### ISSUE THREAD

**Issue by Taher-17** [FeezyHendrix/Insta-mass-account-creator#72]
ModuleNotFoundError: No module named 'pymailutils'

**Comment by byniniko** [comment]
I get the same error :)

**Comment by halperdz** [comment]
You need to use the proper git URL: https://github.com/matteogaito/pymailutils

pip install git+git://github.com/matteogaito/pymailutils.git

or

pip install git+https://github.com/matteogaito/pymailutils.git

Also see the VCS Support section of the pip documentation.
