### ISSUE TITLE
Always error running

### ISSUE THREAD

**Issue by deadfishhackers** [FeezyHendrix/Insta-mass-account-creator#80]
C:\Users\AlienWare\Desktop\Insta-mass-account-creator-master>creator.py
C:\Users\AlienWare\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

DevTools listening on ws://127.0.0.1:53361/devtools/browser/e5ec48a3-9794-48b0-b197-4706e85b2c46
Opening Browser
Browser Opened
INFO:root:Gender: male
INFO:root:Url generated: https://it.fakenamegenerator.com/gen-male-it-it.php
INFO:root:Birthday: January 16, 1950
INFO:root:Username: brunopisano69
Filling email field
Error!, Trying another Proxy 85.187.245.59:53281

DevTools listening on ws://127.0.0.1:53398/devtools/browser/a5139327-ba00-433f-becf-ee98da5c4b5c
Opening Browser

**Comment by FeezyHendrix** [comment]
It's loading the mobile web agent. This has been fixed in the latest pull request #82
