### ISSUE TITLE
String Error on run

### ISSUE THREAD

**Issue by NotNate** [FeezyHendrix/Insta-mass-account-creator#81]
`Filling email field
can only concatenate str (not "NoSuchElementException") to str` is the error that happens every time the program is run.

**Comment by NotNate** [comment]
Mobile web agent was being used, changed it to desktop computer chrome web agent and problem was solved.

**Comment by OliiX** [comment]
How'd you change the user agent? Same issue.

**Comment by tommy2049** [comment]
how did you change from using mobile web agent to desktop agent
