### ISSUE TITLE
can only concatenate str (not "RecursionError") to str

### ISSUE THREAD

**Issue by OliiX** [FeezyHendrix/Insta-mass-account-creator#83]
```
Creating 1 amount of users for this proxy
Opening Browser
Browser Opened
INFO:root:Gender: male
INFO:root:Url generated: https://it.fakenamegenerator.com/gen-male-it-it.php
INFO:root:Birthday: August 21, 1952
INFO:root:Username: galeazzonucci40
Filling email field
<selenium.webdriver.remote.webelement.WebElement (session="7527e09a06dd9f1b1c2b10d4c03f78b2", element="8521944c-17b6-44e7-8467-3b6cb9bf0811")>
galeazzonucci40@gmail.com
Filling fullname field
Filling username field
Filling password field
JL3Ji8ueqjYI
INFO:root:Storing username galeazzonucci40
INFO:root:{'name': 'Galeazzo Nucci', 'username': 'galeazzonucci40', 'password': 'JL3Ji8ueqjYI', 'email': 'galeazzonucci40@gmail.com', 'gender': 'male', 'birthday': 'August 21, 1952'}
can only concatenate str (not "RecursionError") to str
```

**Comment by micalter** [comment]
i get the same issue,how do i solve this

**Comment by itseasy21** [comment]
Solution, on line number 6 in storeusername.py inside modules change `a+` to `ab`

**Comment by FeezyHendrix** [comment]
@itseasy21 can you create a pr for this i would gladly merge.

**Comment by Parham-sagharchi** [comment]
i have these problem,

Opening Browser
Browser Opened
INFO:root:Gender: male
INFO:root:Url generated: https://it.fakenamegenerator.com/gen-male-it-it.php
INFO:root:Birthday: October 8, 1936
INFO:root:Username: damianolombardi40
Filling email field
Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="emailOrPhone"]"}
  (Session info: chrome=83.0.4103.116)

what should i do?
