### ISSUE TITLE
"Sorry, something went wrong creating your account. Please try again"

### ISSUE THREAD

**Issue by MattGoodson** [FeezyHendrix/Insta-mass-account-creator#9]
Whenever the bot tries to make an account this is all Instagram says

**Comment by FeezyHendrix** [comment]
A screenshot and log would be nice and probably the issue might be related to Instagram not allowing you to create an account.

**Comment by MattGoodson** [comment]
![capture](https://user-images.githubusercontent.com/32989567/44048571-51d9b03a-9ef7-11e8-9691-ae8c67dc959b.PNG)

**Comment by MattGoodson** [comment]
I didn't change anything other than the password, firebase url, and proxy server.

**Comment by MattGoodson** [comment]
Switched proxy server to a Swedish sever (it was my 12th different proxy) and it worked.

**Comment by FeezyHendrix** [comment]
It's better you try the advanced feature of using multiple proxies.

**Comment by MattGoodson** [comment]
Thank you
